use_frameworks!

target 'SJTBKit_Example' do
  pod 'SJTBKit', :path => '../'

  target 'SJTBKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
